# Generated by Django 4.2.4 on 2023-08-27 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_category_alter_posting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
