# Generated by Django 4.2.4 on 2023-08-27 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_alter_posting_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posting',
            new_name='Movie',
        ),
    ]
