# Generated by Django 4.2.4 on 2023-08-27 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_rename_posting_movie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='judul_film',
            new_name='name',
        ),
    ]
