# Generated by Django 4.2.4 on 2023-09-14 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_rename_judul_film_movie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Kids'), (1, 'teenager'), (2, 'mature')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='post_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(to='film.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='movietype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='film.movietype'),
        ),
    ]
