# Generated by Django 4.2.4 on 2023-09-14 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_movietype_remove_movie_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietype',
            name='name',
        ),
    ]
