# Generated by Django 4.2.4 on 2023-09-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.CharField(default=2, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='movietype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.movietype'),
        ),
        migrations.AlterField(
            model_name='movietype',
            name='type',
            field=models.IntegerField(choices=[(0, 'Kids'), (1, 'teenager'), (2, 'mature')]),
        ),
    ]
