# Generated by Django 4.2.4 on 2023-09-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_movie_link_alter_movie_movietype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movietype',
            field=models.IntegerField(choices=[(0, 'Kids'), (1, 'teenager'), (2, 'mature')]),
        ),
        migrations.DeleteModel(
            name='MovieType',
        ),
    ]
