# Generated by Django 4.2.4 on 2023-09-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_alter_movie_movietype_delete_movietype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, upload_to='tumbnails'),
        ),
    ]
