# Generated by Django 4.2.4 on 2023-09-26 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_userprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='user',
        ),
    ]
