# Generated by Django 4.2.4 on 2023-09-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0020_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
