# Generated by Django 4.2.4 on 2023-09-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0024_rename_user_id_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar'),
        ),
    ]
